In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

tf.set_random_seed(777)

In [2]:
a = np.array(pd.read_csv("./heart.csv"))
a = a[:,1:-1]
a[12]

array([ 44.,   1.,   3., 120., 263.,   0.,   0., 173.,   0.,   0.,   1.,
         0.,   1.])

In [3]:
scaler = MinMaxScaler(feature_range=(0,1))
'''
for i in range(1,len(a[0,:])):
    a[:,i] = a[:,i]/np.mean(a[:,i])
'''
a = scaler.fit_transform(a)
a

array([[0.6744186 , 1.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [0.76744186, 1.        , 0.33333333, ..., 0.5       , 1.        ,
        0.        ],
       [0.76744186, 1.        , 0.33333333, ..., 0.5       , 0.66666667,
        0.5       ],
       ...,
       [0.23255814, 1.        , 0.33333333, ..., 1.        , 0.        ,
        1.        ],
       [0.6744186 , 1.        , 0.33333333, ..., 0.        , 0.66666667,
        0.5       ],
       [0.6744186 , 0.        , 0.33333333, ..., 0.5       , 0.        ,
        0.        ]])

In [12]:
data = np.array(a)
x_data = data[:,:-1]
y_data = data[:,[-1]]
'''
for i in range(len(y_data)):
    if y_data[i] == 'No':
        y_data[i] = 0.0
    else:
        y_data[i] = 1.0
'''
#y_data = y_data.reshape(235,1)
x_data = np.array(x_data,dtype=np.float32)
x_data
y_data

array([[1. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0.5],
       [1. ],
       [0. ],
       [0.5],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0.5],
       [0. ],
       [0.5],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0.5],
       [0.5],
       [1. ],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0.5],
       [0. ],
       [0. ],
       [0.5],
      

In [5]:
b = np.array(pd.read_csv("./heart_test.csv"))
b = b[:,1:-1]
'''
for i in range(1,len(b[0,:])):
    b[:,i] = b[:,i]/np.mean(b[:,i])
'''
b = scaler.fit_transform(b)

x_test = b[:,:-1]
y_test = b[:,-1]
'''
for i in range(len(y_data)):
    if y_data[i] == 'No':
        y_data[i] = 0.0
    else:
        y_data[i] = 1.0
'''
y_test = y_test.reshape(57,1)
x_test = np.array(x_test,dtype=np.float32)

In [6]:
num = 12
X = tf.placeholder(tf.float32,[None,num])
Y = tf.placeholder(tf.float32,[None,1])

In [7]:
W = tf.Variable(tf.random_normal([num,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

In [8]:
hypothesis = tf.sigmoid(tf.matmul(X,W)+b)
#hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
#cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis)))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

predicted = tf.cast(hypothesis >0.5,dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y),tf.float32))

In [9]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        sess.run(optimizer, feed_dict= {X:x_data,Y:y_data})
        if step %2000 ==0:
            print(step, sess.run([cost],feed_dict={X:x_data,Y:y_data}))
    print(sess.run([accuracy],feed_dict={X:x_test,Y:y_test}))
    print(sess.run([accuracy],feed_dict={X:x_data,Y:y_data}))

0 [1.0791091]
2000 [0.47655097]
4000 [0.47294226]
6000 [0.47177026]
8000 [0.47130755]
10000 [0.47109827]
12000 [0.4709949]
14000 [0.47094104]
16000 [0.4709119]
18000 [0.47089583]
20000 [0.47088683]
[0.40350878]
[0.5702128]


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import utils


# error fix link 
# :https://www.kaggle.com/pratsiuk/valueerror-unknown-label-type-continuous 
lab_enc = preprocessing.LabelEncoder()

#np.ravel 이게 뭔지 잘 모르겠네

training_scores_y = lab_enc.fit_transform(np.ravel(y_data))
print(np.ravel(y_data).shape)
lr = LogisticRegression(solver='lbfgs')
lr.fit(x_data,training_scores_y)

print("Test Accuracy {:.2f}%".format(lr.score(x_test,y_test)*100))

(235,)


ValueError: Classification metrics can't handle a mix of continuous and binary targets