In [4]:
import tensorflow as tf
import numpy as np

In [5]:
x_data = np.array([[0,0],[1,0],[0,1],[1,1]])
y_data = np.array([[0],[1],[1],[0]])

In [6]:
#num of hidden1 nodes
num = 3

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_normal([2,num]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([num]),name = 'bias1')
W2 = tf.Variable(tf.random_normal([num,1]),name = 'weight2')
b2 = tf.Variable(tf.random_normal([1]),name = 'bias2')

layer1 =tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis =tf.sigmoid(tf.matmul(layer1,W2)+b2)

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

predict = tf.cast(hypothesis > 0.5 , dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict,Y),dtype = tf.float32))

In [13]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict = {X:x_data, Y:y_data})
        if step % 1000 == 0:
            print(step,sess.run(cost,feed_dict = {X:x_data , Y:y_data}))
    
    h,c,a = sess.run([hypothesis,predict,accuracy],feed_dict = {X:x_data , Y:y_data})
    print(h,c,a)

0 0.6912062
1000 0.6567054
2000 0.3492815
3000 0.110035956
4000 0.05664486
5000 0.037009384
6000 0.027194377
7000 0.021389445
8000 0.017579952
9000 0.014898192
10000 0.012912723
[[0.01383764]
 [0.9884505 ]
 [0.98830855]
 [0.01423725]] [[0.]
 [1.]
 [1.]
 [0.]] 1.0


In [16]:
a = np.array([1,2,3,4,5])
b= np.array([1,1])

In [17]:
np.convolve(a,b)

array([1, 3, 5, 7, 9, 5])

In [18]:
from scipy import signal

In [19]:
signal.convolve2d([[1,2,3],[2,3,2],[1,3,2]],[[1,2],[0,-1]])

array([[ 1,  4,  7,  6],
       [ 2,  6,  6,  1],
       [ 1,  3,  5,  2],
       [ 0, -1, -3, -2]])

In [23]:
p = [3,2,1]

In [24]:
a = abs(p[1]) if p[0] == 1 else abs(p[2])*3

In [25]:
a

3