In [18]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [19]:
xy = np.loadtxt("./data-04-zoo.csv", delimiter = ',', dtype = np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [20]:
#number of feature
num = 16
#number of outputs
nb_classes = 7

X = tf.placeholder(tf.float32,[None,num])
Y = tf.placeholder(tf.int32,[None,1])

Y_one_hot = tf.one_hot(Y,nb_classes) # shape =(?,1,7)
#after one_hot dimension goes high so should reshape the one_hot
Y_one_hot = tf.reshape(Y_one_hot,[-1,nb_classes]) #shape = (?,7)

W = tf.Variable(tf.random_normal([num,nb_classes]),name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]),name = 'bias')

logits = tf.matmul(X,W) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels = Y_one_hot)
cost = tf.reduce_mean(cost_i)
#cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

prediction = tf.argmax(hypothesis,1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [22]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer,feed_dict = {X:x_data,Y:y_data})
        if step % 200 ==0:
            loss,acc = sess.run([cost,accuracy], feed_dict = {X:x_data,Y:y_data})
            print(loss,acc)

3.8084235 0.17821783
0.45530686 0.8712871
0.29777464 0.9405941
0.21953349 0.95049506
0.17129335 0.96039605
0.13842118 0.96039605
0.11484323 0.990099
0.09741655 0.990099
0.08422277 1.0
0.07400427 1.0


In [11]:
x = [0,1,2]
x = tf.one_hot(x,depth = 3).eval(session=sess)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
