In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Training and Test Datasets

In [2]:
tf.set_random_seed(777)
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [4]:
#let's see how many features do we have & how many outputs are there
num = 3
num_out = 3

In [5]:
X = tf.placeholder("float",[None,num])
Y = tf.placeholder("float",[None,3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [10]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#tf.cast --> if bool true =1 false =0
#tf.cast(x > n) --> over n =1 under n =0

In [11]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 5.73203 [[ 0.7288166   0.7153621  -1.1801533 ]
 [-0.57753736 -0.12988332  1.6072978 ]
 [ 0.48373488 -0.51433605 -2.02127   ]]
1 3.317995 [[ 0.6621908   0.7479632  -1.1461285 ]
 [-0.8194891   0.03000021  1.689366  ]
 [ 0.23214608 -0.33772916 -1.9462881 ]]
2 2.0218027 [[ 0.6434202   0.74127686 -1.1206716 ]
 [-0.81161296 -0.00900121  1.7204912 ]
 [ 0.2086665  -0.3507957  -1.909742  ]]
3 1.9710886 [[ 0.6235321   0.7400824  -1.099589  ]
 [-0.8096771  -0.01636279  1.725917  ]
 [ 0.17870612 -0.33665746 -1.8939198 ]]
4 1.9446774 [[ 0.60733104  0.7366499  -1.0799555 ]
 [-0.7900784  -0.03363196  1.7235874 ]
 [ 0.16691469 -0.3340635  -1.8847224 ]]
5 1.9235673 [[ 0.59031737  0.7351024  -1.0613943 ]
 [-0.7749677  -0.0404885   1.7153332 ]
 [ 0.150766   -0.322094   -1.8805432 ]]
6 1.9035923 [[ 0.57437915  0.7326286  -1.0429822 ]
 [-0.75527775 -0.05152002  1.7066748 ]
 [ 0.13977794 -0.31497926 -1.8766699 ]]
7 1.8840803 [[ 0.5581266   0.7307179  -1.024819  ]
 [-0.73775685 -0.05928205  1.696916  ]
 [ 

159 0.7425573 [[-0.9329874   0.32976285  0.86725026]
 [ 0.30578613  0.12495825  0.46913254]
 [-0.37128723 -0.4004798  -1.2801033 ]]
160 0.7402977 [[-0.9389806   0.32821035  0.874796  ]
 [ 0.30803508  0.12709346  0.4647484 ]
 [-0.37131408 -0.40190816 -1.2786481 ]]
161 0.73807037 [[-0.9449464   0.32667732  0.88229483]
 [ 0.31025386  0.129199    0.4604241 ]
 [-0.3713168  -0.40330988 -1.2772437 ]]
162 0.7358748 [[-0.95088506  0.32516366  0.88974714]
 [ 0.3124428   0.13127501  0.45615914]
 [-0.37129554 -0.4046852  -1.2758896 ]]
163 0.7337105 [[-0.9567968   0.32366922  0.8971534 ]
 [ 0.31460214  0.13332172  0.4519531 ]
 [-0.3712506  -0.4060343  -1.2745855 ]]
164 0.7315767 [[-0.962682    0.3221939   0.9045139 ]
 [ 0.31673208  0.13533925  0.4478056 ]
 [-0.3711822  -0.40735742 -1.2733308 ]]
165 0.72947294 [[-0.9685408   0.32073754  0.91182905]
 [ 0.31883293  0.13732778  0.44371623]
 [-0.3710906  -0.40865487 -1.272125  ]]
166 0.72739875 [[-0.9743735   0.31930003  0.9190993 ]
 [ 0.32090488  0.139